### ISSUE TITLE
Ignore warning/errors with composer --no-interaction

### ISSUE THREAD

**Issue by roukmoute** [sroze/companienv#15]
I think it could be a good things, with CircleCI for example, to ignore .env if it is not exist and create/copy/paste .env from the dist file or just ignore if .env.dist does not exist.

For example, currently we use Docker in CircleCI and we just copy our .env and not .env.dist.

I can do a P.R. but I would like to know your point of view of what you prefer.

**Comment by sroze** [comment]
Thank you for the issue. Do you mean you’d like a “non-interactive” mode
where it just copies the dist file to the .env file? If yes, then I believe
it’s definitely valuable! (I actually don’t use it in this situation but
would have expected it to work this way :))

**Comment by roukmoute** [comment]
Resolved by https://github.com/sroze/companienv/pull/16
